name: Node CI

inputs:
  node-version:
    required: false
    default: 20
  sonar-token:
    required: false
  sonar-host-url:
    required: false

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'
    - run: npm ci || npm install
      shell: bash
    - id: build
      run: npm run build --if-present
      shell: bash
    - uses: actions/upload-artifact@v4
      with:
        name: build
        path: build
        if-no-files-found: ignore    
    - id: lint
      run: npm run lint --if-present
      shell: bash
    - run: npm test --if-present
      shell: bash
    - run: npm run test:e2e --if-present
      shell: bash
    - run: npm run test:cov --if-present
      shell: bash
    - uses: actions/upload-artifact@v4
      with:
        name: coverage
        path: coverage
        if-no-files-found: ignore
    - if: ${{ inputs.sonar-token || inputs.sonar-host-url }}
      uses: sonarsource/sonarqube-scan-action@master
      continue-on-error: true
      env:
        SONAR_TOKEN: ${{ inputs.sonar-token }}
        SONAR_HOST_URL: ${{ inputs.sonar-host-url }}
    - if: ${{ always() && github.event_name == 'pull_request' }}
      uses: peter-evans/create-or-update-comment@v3
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          # Node CI

          Node CI completed!

          ---

          ## Steps

          | Step      | Status                     |
          | --------- | -------------------------- |
          | **Build** | ${{ steps.build.outcome }} |
          | **Lint**  | ${{ steps.lint.outcome }}  |
      continue-on-error: true

branding:
  icon: 'git-branch'
  color: 'blue'
