name: Node CI

inputs:
  sonar-token:
    required: false
  sonar-host-url:
    required: false

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    - run: npm ci
      shell: bash
    - run: npm run build --if-present
      shell: bash
    - run: npm run lint --if-present
      shell: bash
    - run: npm run test:cov --if-present
      shell: bash
    - uses: actions/upload-artifact@v4
      with:
        name: coverage
        path: coverage
        if-no-files-found: ignore
    - name: SonarQube
      if: ${{ inputs.sonar-token || inputs.sonar-host-url }}
      uses: sonarsource/sonarqube-scan-action@master
      continue-on-error: true
      env:
        SONAR_TOKEN: ${{ inputs.sonar-token }}
        SONAR_HOST_URL: ${{ inputs.sonar-host-url }}

branding:
  icon: 'git-branch'
  color: 'blue'
