name: CI

on:
  - push
  - workflow_dispatch

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/upload-artifact@v4
        with:
          name: action-${{ matrix.os }}
          path: action.yml
      - uses: actions/checkout@v4
        with:
          repository: gabrielrufino/node-template
      - uses: actions/download-artifact@v4
      - uses: ./action-${{ matrix.os }}/
