name: CI

on:
  - pull_request
  - push
  - workflow_dispatch

jobs:
  upload-action:
    name: Upload action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/upload-artifact@v4
        with:
          name: action
          path: action.yml
  test:
    name: 'Test: default usage'
    runs-on: ubuntu-latest
    needs:
      - upload-action
    steps:
      - uses: actions/checkout@v4
        with:
          repository: gabrielrufino/node-template
      - uses: actions/download-artifact@v4
      - uses: ./action/
  test-using-except:
    name: "Test: using 'except'"
    runs-on: ubuntu-latest
    needs:
      - upload-action
    steps:
      - uses: actions/checkout@v4
        with:
          repository: gabrielrufino/node-template
      - uses: actions/download-artifact@v4
      - uses: ./action/
        with:
          except: build
  test-in-different-operating-systems:
    name: 'Test: different operating systems'
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    needs:
      - upload-action
    steps:
      - uses: actions/checkout@v4
        with:
          repository: gabrielrufino/node-template
      - uses: actions/download-artifact@v4
      - uses: ./action/

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
